export const ADD_CATEGORY = "ADD_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const SELECT_TASK = "SELECT_TASK";
export const MAKE_TASK_EDITABLE = "MAKE_TASK_EDITABLE";
export const IS_CATEGORY_EDITABLE = "IS_CATEGORY_EDITABLE";
export const ADD_DESCRIPTION = "ADD_DESCRIPTION";
export const MARK_US_COMPLETED = "MARK_US_COMPLETED";
export const DELETE_TASK = "DELETE_TASK";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";


